[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
user=root

[program:munge]
command=/usr/sbin/munged -f -F
autostart=true
autorestart=true
stderr_logfile=/var/log/munge.err.log
stdout_logfile=/var/log/munge.out.log

[program:slurmctld]
command=/usr/sbin/slurmctld -D -vvv
autostart=true
autorestart=true
stderr_logfile=/var/log/slurmctld.err.log
stdout_logfile=/var/log/slurmctld.out.log

[program:slurmd]
command=/usr/sbin/slurmd -D -vvv
autostart=true
autorestart=true
stderr_logfile=/var/log/slurmd.err.log
stdout_logfile=/var/log/slurmd.out.log

