AuthType=auth/munge
AuthInfo=/run/munge/munge.socket.2
DbdHost=localhost
DbdPort=7031
SlurmUser=root
DebugLevel=3
LogFile=/var/log/slurm/slurmdbd.log
PidFile=/run/slurmdbd/slurmdbd.pid
StorageType=accounting_storage/mysql
StorageHost=localhost
StorageUser=slurm
StoragePass=slurm_pass
