#!/command/with-contenv sh
set -eu

until [ -S /run/munge/munge.socket.2 ]; do
    echo "[slurmdbd.run]: sock /run/munge/munge.socket.2 not ready" >&2
    sleep 1
done

until [ -S /run/mariadb/mariadb.sock ]; do
    echo "[slurmdbd.run]: sock /run/mariadb/mariadb.sock not ready" >&2
    sleep 1
done

export MYSQL_UNIX_PORT=/run/mariadb/mariadb.sock

if ! mariadb -uroot -e "SELECT 1 FROM mysql.user LIMIT 1" >/dev/null 2>&1; then
    echo "[slurmdbd.run]: mariadb not ready" >&2
    exit 1
fi

mysql -uroot <<'SQL'
CREATE DATABASE IF NOT EXISTS slurm_acct_db;
CREATE USER IF NOT EXISTS 'slurm'@'localhost' IDENTIFIED BY 'slurm_pass';
CREATE USER IF NOT EXISTS 'slurm'@'127.0.0.1' IDENTIFIED BY 'slurm_pass';
GRANT ALL PRIVILEGES ON slurm_acct_db.* TO 'slurm'@'localhost';
GRANT ALL PRIVILEGES ON slurm_acct_db.* TO 'slurm'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

exec /usr/sbin/slurmdbd -D -vv
