# slurm minimal configuration
ClusterName=simulator
SlurmctldHost=ThisIsReplacedAtRuntime
ProctrackType=proctrack/linuxproc
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=root
StateSaveLocation=/var/spool/slurmctld
AuthInfo=/run/munge/munge.socket.2
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
AccountingStorageType=accounting_storage/slurmdbd
SlurmctldDebug=info
SlurmdDebug=info
SlurmdParameters=config_overrides
AccountingStorageHost=localhost
AccountingStoragePort=6819

# Nodes
NodeName=node01 NodeHostName=localhost
# Not detected ?
# NodeName=node[02-10] NodeHostName=node[02-10]

# Partitions
PartitionName=short Nodes=node01 Default=YES State=UP OverSubscribe=NO MaxTime=14-00:00:00
