---
name: Test Image

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: Image version to pull
        default: latest
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install slurm-client
        run: |
          sudo apt-get update && sudo apt-get install -y slurm-client munge
      - name: Pull and run Slurm image
        run: |
          docker pull ghcr.io/zckv/slurm-small-sim:${{ inputs.image_version }}
          docker run -d -p 6817:6817 -p 6818:6818 -p 6819:6819 \
            -e MUNGE_KEY_BASE64="${{ secrets.MUNGE_KEY_BASE64 }}" \
            ghcr.io/zckv/slurm-small-sim:${{ inputs.image_version }}
      - name: Setup Munge
        run: |
          mkdir -p /etc/munge
          base64 -d tests/munge.key.base64 > munge.key
          sudo ls -la /etc/munge
          echo ""
          sudo cp munge.key /etc/munge/munge.key
          sudo ls -la /etc/munge
          echo ""
          sudo chmod 400 /etc/munge/munge.key          
          sudo chown munge:munge /etc/munge/munge.key
          sudo chown root:root /var/log/munge -R
          sudo munged -vv
      # TODO: add an slurm setup action ? 
      - name: Light test
        run: sinfo
